### ISSUE TITLE
Optional Internet Gateway

### ISSUE THREAD

**Issue by bruvduroiu** [opszero/terraform-aws-kubespot#406]
Hi OpsZero team,

I have a fully private EKS cluster, which never needs to be accessed from the Internet. 

I would like to only provision a NAT Gateway, instead of an Internet Gateway.

Is it possible to only optionally create an Internet Gateway? I can contribute this feature if needed

**Comment by bruvduroiu** [comment]
I found `vars.enable_egress_only_internet_gateway`, I'm guessing this should satisfy this requirement?

**Comment by abhiyerra** [comment]
use `nat_enabled = true` and launch node_groups in the private_subnet.
