### ISSUE TITLE
Output aws_iam_openid_connect_provider.cluster.arn

### ISSUE THREAD

**Issue by ethangamma24** [opszero/terraform-aws-kubespot#412]
I've got a usecase for an AWS Load Balancer Controller added on to the EKS cluster provisioned by this module, the Terraform module for which requires the cluster's OIDC Provider ARN. Adding this output would be a huge help.

**Comment by ethangamma24** [comment]
I'm currently working on this change in a fork, just wanted to go ahead and open the issue :)

**Comment by abhiyerra** [comment]
Thank you!
